version = 0.1
[default.deploy.parameters]
stack_name = "marco-helloworld"
resolve_s3 = true
s3_prefix = "marco-helloworld"
region = "us-west-2"
capabilities = "CAPABILITY_IAM"
disable_rollback = false
image_repositories = []
